export type RootStackParamList = {
  Main: undefined;
  Home: undefined;
  Registration: undefined;
  Login: undefined;
  ThemeInspector: undefined;
  StressRate: undefined;
  StressTrigger: undefined;
  StressActivityType: undefined;
  Activity: undefined;
  Modal: undefined;
  Tutorial: undefined;
  KitActivation: undefined;
  AboutVR: undefined;
  StressActivityToDo: undefined;
  VRMet: undefined;
  Support: undefined;
  PathEnding: undefined;
  Profile: undefined;
  Statistics: undefined;
  HowTo: undefined;
  VRDemo: undefined;
  KitAssemble: undefined;
  Library: undefined;
};