import { translate } from './localization';
import config from '../../env';

export const TIPS_VR = () => translate('screens.Activity.tipsVr');
export const TIPS_VIDEO = () => translate('screens.Activity.tipsVideo');
export const TIPS_AUDIO = () => translate('screens.Activity.tipsAudio');

export const ANALYTICS_EVENTS = {
  FUNNEL_LOGIN: 'funnel_login',
  FUNNEL_REGISTER_ENTER: 'funnel_registration_enter',
  FUNNEL_REGISTER_COMPLETE: 'funnel_registration_complete',
  FUNNEL_ONBOARD_COMPLETE: 'funnel_onboarding_complete',
  FUNNEL_WIZARD_FINISH: 'funnel_tutorial_complete',
  FUNNEL_WIZARD_ABORT: 'funnel_tutorial_cancel',
};

export const ACTIVITIES_TYPES = {
  text: 'text',
  audio: 'audio',
  activity: 'activity',
};

export const LIFESAVER_ACTIVITIES = [
  {
    id: 'breath-sync',
    free: true,
    type: ACTIVITIES_TYPES.activity,
    category: 'practical',
  },
  {
    id: 'deep-breath-sync',
    free: true,
    type: ACTIVITIES_TYPES.activity,
    category: 'practical',
  },
  {
    id: 'bubbles-wrapper',
    type: ACTIVITIES_TYPES.activity,
    category: 'practical',
  },
];

export const LIFESAVER_AUDIOS = lang => [
  {
    id: `LS_HOME_calm_${lang}.mp3`,
    title: 'Calm',
    source: `lifesaver/LS_HOME_calm_${lang}.mp3`,
    type: ACTIVITIES_TYPES.audio,
    category: 'practical',
  },
  {
    id: `LS_WORK_visualization_${lang}.mp3`,
    title: 'Visualization',
    source: `lifesaver/LS_WORK_visualization_${lang}.mp3`,
    type: ACTIVITIES_TYPES.audio,
    category: 'practical',
  },
  {
    id: `LS_PARTY_move_your_attention_${lang}.mp3`,
    title: 'Move your attention',
    source: `lifesaver/LS_PARTY_move_your_attention_${lang}.mp3`,
    type: ACTIVITIES_TYPES.audio,
    category: 'practical',
  },
  {
    id: `LS_OTHER_love_${lang}.mp3`,
    title: 'Love',
    source: `lifesaver/LS_OTHER_love_${lang}.mp3`,
    type: ACTIVITIES_TYPES.audio,
    category: 'practical',
  },
  {
    id: `LS_WORK_calm_${lang}.mp3`,
    title: 'Calm',
    source: `lifesaver/LS_WORK_calm_${lang}.mp3`,
    type: ACTIVITIES_TYPES.audio,
    category: 'practical',
  },
  {
    id: `LS_STREET_breath_${lang}.mp3`,
    title: 'Breath',
    source: `lifesaver/LS_STREET_breath_${lang}.mp3`,
    type: ACTIVITIES_TYPES.audio,
    category: 'practical',
  },
  {
    id: `LS_WORK_positive_perspective_${lang}.mp3`,
    title: 'Perspective',
    source: `lifesaver/LS_WORK_positive_perspective_${lang}.mp3`,
    type: ACTIVITIES_TYPES.audio,
    category: 'practical',
  },
  {
    id: `LS_STREET_pause_${lang}.mp3`,
    title: 'Pause',
    source: `lifesaver/LS_STREET_pause_${lang}.mp3`,
    type: ACTIVITIES_TYPES.audio,
    category: 'practical',
  },
  {
    id: `LS_HOME_compassion_${lang}.mp3`,
    title: 'Compassion',
    source: `lifesaver/LS_HOME_compassion_${lang}.mp3`,
    type: ACTIVITIES_TYPES.audio,
    category: 'practical',
  },
];

export const LIFESAVER_READS = () => [
  {
    id: 'readwork1',
    title: translate('contents.LIFESAVER_READS.readwork1-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'work',
    pages: [
      translate('contents.LIFESAVER_READS.readwork1-1'),
      translate('contents.LIFESAVER_READS.readwork1-2'),
      translate('contents.LIFESAVER_READS.readwork1-3'),
      translate('contents.LIFESAVER_READS.readwork1-4'),
    ],
  },
  {
    id: 'readwork2',
    title: translate('contents.LIFESAVER_READS.readwork2-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'work',
    pages: [
      translate('contents.LIFESAVER_READS.readwork2-1'),
      translate('contents.LIFESAVER_READS.readwork2-2'),
      translate('contents.LIFESAVER_READS.readwork2-3'),
      translate('contents.LIFESAVER_READS.readwork2-4'),
    ],
  },
  {
    id: 'readwork3',
    title: translate('contents.LIFESAVER_READS.readwork3-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'work',
    pages: [
      translate('contents.LIFESAVER_READS.readwork3-1'),
      translate('contents.LIFESAVER_READS.readwork3-2'),
      translate('contents.LIFESAVER_READS.readwork3-3'),
      translate('contents.LIFESAVER_READS.readwork3-4'),
    ],
  },
  {
    id: 'readwork4',
    title: translate('contents.LIFESAVER_READS.readwork4-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'work',
    pages: [
      translate('contents.LIFESAVER_READS.readwork4-1'),
      translate('contents.LIFESAVER_READS.readwork4-2'),
      translate('contents.LIFESAVER_READS.readwork4-3'),
      translate('contents.LIFESAVER_READS.readwork4-4'),
    ],
  },
  {
    id: 'readwork5',
    title: translate('contents.LIFESAVER_READS.readwork5-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'work',
    pages: [
      translate('contents.LIFESAVER_READS.readwork5-1'),
      translate('contents.LIFESAVER_READS.readwork5-2'),
      translate('contents.LIFESAVER_READS.readwork5-3'),
      translate('contents.LIFESAVER_READS.readwork5-4'),
    ],
  },
  {
    id: 'readwork6',
    title: translate('contents.LIFESAVER_READS.readwork6-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'work',
    pages: [
      translate('contents.LIFESAVER_READS.readwork6-1'),
      translate('contents.LIFESAVER_READS.readwork6-2'),
      translate('contents.LIFESAVER_READS.readwork6-3'),
      translate('contents.LIFESAVER_READS.readwork6-4'),
    ],
  },
  {
    id: 'aboutfamily1',
    title: translate('contents.LIFESAVER_READS.aboutfamily1-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'family',
    pages: [
      translate('contents.LIFESAVER_READS.aboutfamily1-1'),
      translate('contents.LIFESAVER_READS.aboutfamily1-2'),
      translate('contents.LIFESAVER_READS.aboutfamily1-3'),
      translate('contents.LIFESAVER_READS.aboutfamily1-4'),
    ],
  },
  {
    id: 'aboutfamily2',
    title: translate('contents.LIFESAVER_READS.aboutfamily2-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'family',
    pages: [
      translate('contents.LIFESAVER_READS.aboutfamily2-1'),
      translate('contents.LIFESAVER_READS.aboutfamily2-2'),
      translate('contents.LIFESAVER_READS.aboutfamily2-3'),
      translate('contents.LIFESAVER_READS.aboutfamily2-4'),
    ],
  },
  {
    id: 'aboutfamily3',
    title: translate('contents.LIFESAVER_READS.aboutfamily3-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'family',
    pages: [
      translate('contents.LIFESAVER_READS.aboutfamily3-1'),
      translate('contents.LIFESAVER_READS.aboutfamily3-2'),
      translate('contents.LIFESAVER_READS.aboutfamily3-3'),
      translate('contents.LIFESAVER_READS.aboutfamily3-4'),
    ],
  },
  {
    id: 'aboutfamily4',
    title: translate('contents.LIFESAVER_READS.aboutfamily4-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'family',
    pages: [
      translate('contents.LIFESAVER_READS.aboutfamily4-1'),
      translate('contents.LIFESAVER_READS.aboutfamily4-2'),
      translate('contents.LIFESAVER_READS.aboutfamily4-3'),
      translate('contents.LIFESAVER_READS.aboutfamily4-4'),
    ],
  },
  {
    id: 'aboutfamily5',
    title: translate('contents.LIFESAVER_READS.aboutfamily5-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'family',
    pages: [
      translate('contents.LIFESAVER_READS.aboutfamily5-1'),
      translate('contents.LIFESAVER_READS.aboutfamily5-2'),
      translate('contents.LIFESAVER_READS.aboutfamily5-3'),
      translate('contents.LIFESAVER_READS.aboutfamily5-4'),
    ],
  },
  {
    id: 'aboutfamily6',
    title: translate('contents.LIFESAVER_READS.aboutfamily6-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'family',
    pages: [
      translate('contents.LIFESAVER_READS.aboutfamily6-1'),
      translate('contents.LIFESAVER_READS.aboutfamily6-2'),
      translate('contents.LIFESAVER_READS.aboutfamily6-3'),
      translate('contents.LIFESAVER_READS.aboutfamily6-4'),
    ],
  },
  {
    id: 'aboutcontext1',
    title: translate('contents.LIFESAVER_READS.aboutcontext1-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'social',
    pages: [
      translate('contents.LIFESAVER_READS.aboutcontext1-1'),
      translate('contents.LIFESAVER_READS.aboutcontext1-2'),
      translate('contents.LIFESAVER_READS.aboutcontext1-3'),
      translate('contents.LIFESAVER_READS.aboutcontext1-4'),
    ],
  },
  {
    id: 'aboutcontext2',
    title: translate('contents.LIFESAVER_READS.aboutcontext2-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'social',
    pages: [
      translate('contents.LIFESAVER_READS.aboutcontext2-1'),
      translate('contents.LIFESAVER_READS.aboutcontext2-2'),
      translate('contents.LIFESAVER_READS.aboutcontext2-3'),
      translate('contents.LIFESAVER_READS.aboutcontext2-4'),
    ],
  },
  {
    id: 'aboutcontext3',
    title: translate('contents.LIFESAVER_READS.aboutcontext3-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'social',
    pages: [
      translate('contents.LIFESAVER_READS.aboutcontext3-1'),
      translate('contents.LIFESAVER_READS.aboutcontext3-2'),
      translate('contents.LIFESAVER_READS.aboutcontext3-3'),
      translate('contents.LIFESAVER_READS.aboutcontext3-4'),
    ],
  },
  {
    id: 'aboutcontext4',
    title: translate('contents.LIFESAVER_READS.aboutcontext4-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'social',
    pages: [
      translate('contents.LIFESAVER_READS.aboutcontext4-1'),
      translate('contents.LIFESAVER_READS.aboutcontext4-2'),
      translate('contents.LIFESAVER_READS.aboutcontext4-3'),
      translate('contents.LIFESAVER_READS.aboutcontext4-4'),
    ],
  },
  {
    id: 'aboutcontext5',
    title: translate('contents.LIFESAVER_READS.aboutcontext5-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'social',
    pages: [
      translate('contents.LIFESAVER_READS.aboutcontext5-1'),
      translate('contents.LIFESAVER_READS.aboutcontext5-2'),
      translate('contents.LIFESAVER_READS.aboutcontext5-3'),
      translate('contents.LIFESAVER_READS.aboutcontext5-4'),
    ],
  },
  {
    id: 'aboutcontext6',
    title: translate('contents.LIFESAVER_READS.aboutcontext6-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'social',
    pages: [
      translate('contents.LIFESAVER_READS.aboutcontext6-1'),
      translate('contents.LIFESAVER_READS.aboutcontext6-2'),
      translate('contents.LIFESAVER_READS.aboutcontext6-3'),
      translate('contents.LIFESAVER_READS.aboutcontext6-4'),
    ],
  },
  {
    id: 'aboutrelations1',
    title: translate('contents.LIFESAVER_READS.aboutrelations1-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'relationship',
    pages: [
      translate('contents.LIFESAVER_READS.aboutrelations1-1'),
      translate('contents.LIFESAVER_READS.aboutrelations1-2'),
      translate('contents.LIFESAVER_READS.aboutrelations1-3'),
      translate('contents.LIFESAVER_READS.aboutrelations1-4'),
    ],
  },
  {
    id: 'aboutrelations2',
    title: translate('contents.LIFESAVER_READS.aboutrelations2-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'relationship',
    pages: [
      translate('contents.LIFESAVER_READS.aboutrelations2-1'),
      translate('contents.LIFESAVER_READS.aboutrelations2-2'),
      translate('contents.LIFESAVER_READS.aboutrelations2-3'),
      translate('contents.LIFESAVER_READS.aboutrelations2-4'),
    ],
  },
  {
    id: 'aboutrelations3',
    title: translate('contents.LIFESAVER_READS.aboutrelations3-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'relationship',
    pages: [
      translate('contents.LIFESAVER_READS.aboutrelations3-1'),
      translate('contents.LIFESAVER_READS.aboutrelations3-2'),
      translate('contents.LIFESAVER_READS.aboutrelations3-3'),
      translate('contents.LIFESAVER_READS.aboutrelations3-4'),
    ],
  },
  {
    id: 'aboutrelations4',
    title: translate('contents.LIFESAVER_READS.aboutrelations4-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'relationship',
    pages: [
      translate('contents.LIFESAVER_READS.aboutrelations4-1'),
      translate('contents.LIFESAVER_READS.aboutrelations4-2'),
      translate('contents.LIFESAVER_READS.aboutrelations4-3'),
      translate('contents.LIFESAVER_READS.aboutrelations4-4'),
    ],
  },
  {
    id: 'aboutrelations5',
    title: translate('contents.LIFESAVER_READS.aboutrelations5-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'relationship',
    pages: [
      translate('contents.LIFESAVER_READS.aboutrelations5-1'),
      translate('contents.LIFESAVER_READS.aboutrelations5-2'),
      translate('contents.LIFESAVER_READS.aboutrelations5-3'),
      translate('contents.LIFESAVER_READS.aboutrelations5-4'),
    ],
  },
  {
    id: 'aboutrelations6',
    title: translate('contents.LIFESAVER_READS.aboutrelations6-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'relationship',
    pages: [
      translate('contents.LIFESAVER_READS.aboutrelations6-1'),
      translate('contents.LIFESAVER_READS.aboutrelations6-2'),
      translate('contents.LIFESAVER_READS.aboutrelations6-3'),
      translate('contents.LIFESAVER_READS.aboutrelations6-4'),
    ],
  },
  {
    id: 'aboutstudy1',
    title: translate('contents.LIFESAVER_READS.aboutstudy1-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'studies',
    pages: [
      translate('contents.LIFESAVER_READS.aboutstudy1-1'),
      translate('contents.LIFESAVER_READS.aboutstudy1-2'),
      translate('contents.LIFESAVER_READS.aboutstudy1-3'),
      translate('contents.LIFESAVER_READS.aboutstudy1-4'),
    ],
  },
  {
    id: 'aboutstudy2',
    title: translate('contents.LIFESAVER_READS.aboutstudy2-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'studies',
    pages: [
      translate('contents.LIFESAVER_READS.aboutstudy2-1'),
      translate('contents.LIFESAVER_READS.aboutstudy2-2'),
      translate('contents.LIFESAVER_READS.aboutstudy2-3'),
      translate('contents.LIFESAVER_READS.aboutstudy2-4'),
    ],
  },
  {
    id: 'aboutstudy3',
    title: translate('contents.LIFESAVER_READS.aboutstudy3-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'studies',
    pages: [
      translate('contents.LIFESAVER_READS.aboutstudy3-1'),
      translate('contents.LIFESAVER_READS.aboutstudy3-2'),
      translate('contents.LIFESAVER_READS.aboutstudy3-3'),
      translate('contents.LIFESAVER_READS.aboutstudy3-4'),
    ],
  },
  {
    id: 'aboutstudy4',
    title: translate('contents.LIFESAVER_READS.aboutstudy4-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'studies',
    pages: [
      translate('contents.LIFESAVER_READS.aboutstudy4-1'),
      translate('contents.LIFESAVER_READS.aboutstudy4-2'),
      translate('contents.LIFESAVER_READS.aboutstudy4-3'),
      translate('contents.LIFESAVER_READS.aboutstudy4-4'),
    ],
  },
  {
    id: 'aboutstudy5',
    title: translate('contents.LIFESAVER_READS.aboutstudy5-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'studies',
    pages: [
      translate('contents.LIFESAVER_READS.aboutstudy5-1'),
      translate('contents.LIFESAVER_READS.aboutstudy5-2'),
      translate('contents.LIFESAVER_READS.aboutstudy5-3'),
      translate('contents.LIFESAVER_READS.aboutstudy5-4'),
    ],
  },
  {
    id: 'aboutstudy6',
    title: translate('contents.LIFESAVER_READS.aboutstudy6-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'studies',
    pages: [
      translate('contents.LIFESAVER_READS.aboutstudy6-1'),
      translate('contents.LIFESAVER_READS.aboutstudy6-2'),
      translate('contents.LIFESAVER_READS.aboutstudy6-3'),
      translate('contents.LIFESAVER_READS.aboutstudy6-4'),
    ],
  },
  {
    id: 'aboutmoney1',
    title: translate('contents.LIFESAVER_READS.aboutmoney1-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'finances',
    pages: [
      translate('contents.LIFESAVER_READS.aboutmoney1-1'),
      translate('contents.LIFESAVER_READS.aboutmoney1-2'),
      translate('contents.LIFESAVER_READS.aboutmoney1-3'),
      translate('contents.LIFESAVER_READS.aboutmoney1-4'),
    ],
  },
  {
    id: 'aboutmoney2',
    title: translate('contents.LIFESAVER_READS.aboutmoney2-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'finances',
    pages: [
      translate('contents.LIFESAVER_READS.aboutmoney2-1'),
      translate('contents.LIFESAVER_READS.aboutmoney2-2'),
      translate('contents.LIFESAVER_READS.aboutmoney2-3'),
      translate('contents.LIFESAVER_READS.aboutmoney2-4'),
    ],
  },
  {
    id: 'aboutmoney3',
    title: translate('contents.LIFESAVER_READS.aboutmoney3-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'finances',
    pages: [
      translate('contents.LIFESAVER_READS.aboutmoney3-1'),
      translate('contents.LIFESAVER_READS.aboutmoney3-2'),
      translate('contents.LIFESAVER_READS.aboutmoney3-3'),
      translate('contents.LIFESAVER_READS.aboutmoney3-4'),
    ],
  },
  {
    id: 'aboutmoney4',
    title: translate('contents.LIFESAVER_READS.aboutmoney4-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'finances',
    pages: [
      translate('contents.LIFESAVER_READS.aboutmoney4-1'),
      translate('contents.LIFESAVER_READS.aboutmoney4-2'),
      translate('contents.LIFESAVER_READS.aboutmoney4-3'),
      translate('contents.LIFESAVER_READS.aboutmoney4-4'),
    ],
  },
  {
    id: 'aboutmoney5',
    title: translate('contents.LIFESAVER_READS.aboutmoney5-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'finances',
    pages: [
      translate('contents.LIFESAVER_READS.aboutmoney5-1'),
      translate('contents.LIFESAVER_READS.aboutmoney5-2'),
      translate('contents.LIFESAVER_READS.aboutmoney5-3'),
      translate('contents.LIFESAVER_READS.aboutmoney5-4'),
    ],
  },
  {
    id: 'aboutmoney6',
    title: translate('contents.LIFESAVER_READS.aboutmoney6-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    contentCategory: 'finances',
    pages: [
      translate('contents.LIFESAVER_READS.aboutmoney6-1'),
      translate('contents.LIFESAVER_READS.aboutmoney6-2'),
      translate('contents.LIFESAVER_READS.aboutmoney6-3'),
      translate('contents.LIFESAVER_READS.aboutmoney6-4'),
    ],
  },
  {
    id: 'aboutother1',
    title: translate('contents.LIFESAVER_READS.aboutother1-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [
      translate('contents.LIFESAVER_READS.aboutother1-1'),
      translate('contents.LIFESAVER_READS.aboutother1-2'),
      translate('contents.LIFESAVER_READS.aboutother1-3'),
      translate('contents.LIFESAVER_READS.aboutother1-4'),
    ],
  },
  {
    id: 'aboutother2',
    title: translate('contents.LIFESAVER_READS.aboutother2-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [
      translate('contents.LIFESAVER_READS.aboutother2-1'),
      translate('contents.LIFESAVER_READS.aboutother2-2'),
      translate('contents.LIFESAVER_READS.aboutother2-3'),
      translate('contents.LIFESAVER_READS.aboutother2-4'),
    ],
  },
  {
    id: 'aboutother3',
    title: translate('contents.LIFESAVER_READS.aboutother3-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [
      translate('contents.LIFESAVER_READS.aboutother3-1'),
      translate('contents.LIFESAVER_READS.aboutother3-2'),
      translate('contents.LIFESAVER_READS.aboutother3-3'),
      translate('contents.LIFESAVER_READS.aboutother3-4'),
    ],
  },
  {
    id: 'aboutother4',
    title: translate('contents.LIFESAVER_READS.aboutother4-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [
      translate('contents.LIFESAVER_READS.aboutother4-1'),
      translate('contents.LIFESAVER_READS.aboutother4-2'),
      translate('contents.LIFESAVER_READS.aboutother4-3'),
      translate('contents.LIFESAVER_READS.aboutother4-4'),
    ],
  },
  {
    id: 'aboutother5',
    title: translate('contents.LIFESAVER_READS.aboutother5-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [
      translate('contents.LIFESAVER_READS.aboutother5-1'),
      translate('contents.LIFESAVER_READS.aboutother5-2'),
      translate('contents.LIFESAVER_READS.aboutother5-3'),
      translate('contents.LIFESAVER_READS.aboutother5-4'),
    ],
  },
  {
    id: 'aboutother6',
    title: translate('contents.LIFESAVER_READS.aboutother6-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [
      translate('contents.LIFESAVER_READS.aboutother6-1'),
      translate('contents.LIFESAVER_READS.aboutother6-2'),
      translate('contents.LIFESAVER_READS.aboutother6-3'),
      translate('contents.LIFESAVER_READS.aboutother6-4'),
    ],
  },
  {
    id: 'laugh-it-out',
    free: true,
    // type: 'read-to-do',
    title: translate('contents.LIFESAVER_READS.laugh-it-out-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [
      translate('contents.LIFESAVER_READS.laugh-it-out-1'),
      translate('contents.LIFESAVER_READS.laugh-it-out-2'),
      translate('contents.LIFESAVER_READS.laugh-it-out-3'),
    ],
  },
  {
    id: 'safe-activity',
    free: true,
    // type: 'read-to-do',
    title: translate('contents.LIFESAVER_READS.safe-activity-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [
      translate('contents.LIFESAVER_READS.safe-activity-1'),
      translate('contents.LIFESAVER_READS.safe-activity-2'),
      translate('contents.LIFESAVER_READS.safe-activity-3'),
    ],
  },
  {
    id: 'connect-with-nature',
    free: true,
    // type: 'read-to-do',
    title: translate('contents.LIFESAVER_READS.connect-with-nature-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [
      translate('contents.LIFESAVER_READS.connect-with-nature-1'),
      translate('contents.LIFESAVER_READS.connect-with-nature-2'),
      translate('contents.LIFESAVER_READS.connect-with-nature-3'),
    ],
  },
  {
    id: 'take-deep-breaths',
    free: true,
    // type: 'read-to-do',
    title: translate('contents.LIFESAVER_READS.take-deep-breaths-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [
      translate('contents.LIFESAVER_READS.take-deep-breaths-1'),
      translate('contents.LIFESAVER_READS.take-deep-breaths-2'),
      translate('contents.LIFESAVER_READS.take-deep-breaths-3'),
    ],
  },
  {
    id: 'calm-image',
    free: true,
    // type: 'read-to-do',
    title: translate('contents.LIFESAVER_READS.calm-image-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [
      translate('contents.LIFESAVER_READS.calm-image-1'),
      translate('contents.LIFESAVER_READS.calm-image-2'),
      translate('contents.LIFESAVER_READS.calm-image-3'),
    ],
  },
  {
    id: 'relaxation',
    free: true,
    // type: 'read-to-do',
    title: translate('contents.LIFESAVER_READS.relaxation-title'),
    type: ACTIVITIES_TYPES.text,
    category: 'learning',
    pages: [translate('contents.LIFESAVER_READS.relaxation-1'), translate('contents.LIFESAVER_READS.relaxation-2')],
  },
];
const DEFAULT_READ_CONTENT_CATEGORY = 'other';
export const getReadsByContentCategory = () =>
  LIFESAVER_READS().reduce((acc, curr) => {
    if (!curr.contentCategory) {
      curr.contentCategory = DEFAULT_READ_CONTENT_CATEGORY;
    }
    if (!(curr.contentCategory in acc)) {
      acc[curr.contentCategory] = [];
    }
    acc[curr.contentCategory].push(curr);
    return acc;
  }, {});

export const ZOHO_SURVEYS = {
  stressSurvey: {
    url: config.surveys.stressSurvey,
  },
  resilienceSurvey: {
    url: config.surveys.resilienceSurvey,
  },
  onboardingSurvey: {
    url: config.surveys.stressSurvey,
    customData: { isOnboarding: true },
  },
  integrationSurvey: {
    url: config.surveys.integrationSurvey,
  },
};
