module.exports = {
  loginButtonSelector: '[data-testid=login-form-submmit-cta]',
  homeLayoutSelector: '[data-testid=home-layout]',
  kitActivationScreenSelector: '[data-testid=KitActivation]',
  stressRateScreen: '[data-testid=StressRate]',
  stressTriggerScreen: '[data-testid=StressTrigger]',
  stressActivityTypeScreen: '[data-testid=StressActivityType]',
  tutorialFirstStepSelector: '[data-testid=welcome-wizard-step-1]',
  tutorialFifthStepSelector: '[data-testid=welcome-wizard-step-5]',
  skipTutorialButtonSelector: '[data-testid=skip-tutorial-button]',
  nextTutorialButtonSelector: '[data-testid=next-tutorial-button]',
  iHaveKitButtonSelector: '[data-testid=tutorial-yes-have-kit]',
  activateKitButtonSelector: '[data-testid=tutorial-go-to-kit-activation]',
  usernameInputSelector: '[data-testid="login-form-username-input"]',
  usernameErrorSelector: '[data-testid="input-component-login-form-username-input"] > [data-testid="error-helper"]',
  passwordInputSelector: '[data-testid="login-form-password-input"]',
  passwordErrorSelector: '[data-testid="input-component-login-form-password-input"] > [data-testid="error-helper"]',
  openDrawerSelector: '[data-testid="open-drawer-button"]',
  drawerActivation: '[data-testid="drawer-activation-button"]',
  kitCodeInput: '[data-testid="kit-activation-code-input"]',
  kitCodeButton: '[data-testid="use-this-code-button"]',
  kitCodeText: '[data-testid="kit-activation-explain-text"]',
  kitCloseDialog: '[data-testid="kit-activation-explain-dialog-close"]',
  kitDialogButton: '[data-testid="kit-activation-explain-dialog-button-0"]',
  aboutVrBackButton: '[data-testid="back-button-about-vr"]',
  relieverButtonSelector: '[data-testid="reliever-button"]',
  backButton: '[data-testid="header-back"]',
  pathEndingButton: '[data-testid="path-endind-button"]',
  pathEndingVote: '[data-testid="path-endind-header-vote"]',
  gotoRegisterButton: '[data-testid="go-to-registration-button"]',
  registerButton: '[data-testid="register-button"]',
  regiterFormRPasswordError:
    '[data-testid="input-component-register-form-rpassword-input"] > [data-testid="error-helper"]',
  regiterFormPasswordError:
    '[data-testid="input-component-register-form-password-input"] > [data-testid="error-helper"]',
  regiterFormEmailError: '[data-testid="input-component-register-form-email-input"] > [data-testid="error-helper"]',
  regiterFormLastnameError:
    '[data-testid="input-component-register-form-lastname-input"] > [data-testid="error-helper"]',
  regiterFormNameError: '[data-testid="input-component-register-form-name-input"] > [data-testid="error-helper"]',
  regiterFormRPasswordInput: '[data-testid="register-form-rpassword-input"]',
  regiterFormPasswordInput: '[data-testid="register-form-password-input"]',
  regiterFormEmailInput: '[data-testid="register-form-email-input"]',
  regiterFormLastnameInput: '[data-testid="register-form-lastname-input"]',
  regiterFormNameInput: '[data-testid="register-form-name-input"]',
  welcomeWizardStep1: '[data-testid="welcome-wizard-step-1"]',
  stressRateRow1: '[data-testid="stress-rate-row-1"]',
  stressRateRow10: '[data-testid="stress-rate-row-10"]',
  stressRateTrigger1: '[data-testid="stress-trigger-1"]',
  stressRateTrigger7: '[data-testid="stress-trigger-7"]',
  stressActivitiesRowReading: '[data-testid="stress-activity-reading"]',
  stressActivitiesRowGuided: '[data-testid="stress-activity-guided"]',
  stressActivitiesRowAudio: '[data-testid="stress-activity-audio"]',
  stressActivitiesReading: '[data-testid="read-activity-carousel"]',
  stressActivitiesGuided: '[data-testid="do-activity"]',
  stressActivitiesAudio: '[data-testid="listen-activity"]',
};
